<?php

namespace FatihOzpolat\JWTValidity;

use FatihOzpolat\JWTValidity\Models\JwtAuthToken;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Foundation\Auth\User as AuthUser;
use Library\Auth\Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends AuthUser implements JWTSubject
{
    use Authenticatable;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(UserObserver::class);
    }

    public function tokens(): MorphMany
    {
        return $this->morphMany(JwtAuthToken::class, 'tokenable');
    }
}
